config/routes.rb
CrdAppRecipe::Application.routes.draw do
  get "feedbacks/create"

  resources :categories

  resources :sources

  resources :portions

  resources :ingredients

  resources :recipes, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  resources :users
  resources :password_resets

  resources :usersbooks, only: [:create, :destroy]
  resources :usersmarks, only: [:create, :index, :set]
  match '/setitem',  to: 'usersmarks#set'
  resources :feedbacks, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/about',  to: 'static_pages#about'
  match '/partnership',  to: 'static_pages#partnership'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/welcome',  to: 'sources#index'

  resources :assignments, only: [:new, :create, :destroy]
  match '/assignout', to: 'assignments#destroy', via: :delete
  match '/remove', to: 'assignments#remove', via: :delete

  
  match '/:locale', to: 'static_pages#home'
  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @since="1 year"
    case 
    when (Date.new(Time.now.year,Time.now.month,1) - Date.new(2013,8,1)).to_i/365 > 1
      @since="#{(Date.new(Time.now.year,Time.now.month,1) - Date.new(2013,8,1)).to_i/365} years"
    when (Date.new(Time.now.year,Time.now.month,1) - Date.new(2013,8,1)).to_i/365 == 0
      @since="#{(Time.now.year * 12 + Time.now.month) - (2013 * 12 + 8)} months"
    end
    
    tips=["Para pesquisar qualquer tipo de queijo basta adicionar <u>queijo%</u>",
      "Se quer encontrar receitas que levam frango ou peito de frango, adicione <u>%frango</u>.",
      "Aceite as nossas sugestoes de ingredientes enquanto digita.",
      "Pode remover os ingredientes um a um ou clicar em <b>Limpar</b> para remover todos de uma vez.",
      "Apos inserir os ingredientes pode pesquisar receitas dos seus livros apenas ou filtrar por categoria."
      ]
    @tip=tips[rand(0..4)]
  	if assigned_in?
      @opt=""
      #@books_only=params[:books_only] if params[:books_only] && params[:books_only]!="0"
      source_opt=params[:source_opt] if params[:source_opt]!="0"
      order_opt=params[:order_opt] if params[:order_opt]!="0"
      #@list_all=params[:all_recipes] if params[:all_recipes]
      @ingredients =Ingredient.all_except(current_list).map(&:name)
      user_id=0 
      user_id=current_user.id if current_user
      #@result=Portion.rank(current_list,params[:category_id],params[:all_recipes],user_id)
      cat_opt=nil
      cat_opt=params[:category_opt] if params[:category_opt] && !params[:category_opt].empty?
      @result=Portion.rank(current_list,cat_opt,params[:all_recipes],user_id, source_opt,order_opt)
      #blacklist=[recipe: Recipe.new]
      @result.each do |r| 
        r[:txt]=r[:recipe].highlight(current_list)
        #if signed_in? && source_opt && !r[:recipe].source.is_usersbook(current_user.id)
        #    blacklist.push(r[:recipe])
        #end
      end
      #filtered_array = @result.select { |r| !blacklist.include? r[:recipe] }
      #filtered_array = @result.reject  { |r| blacklist.include? r[:recipe] }
      #@result=filtered_array
      cat_ids=@result.map{ |d| d[:category_id] }
      @cats=Category.where("id in (?)",cat_ids).order("name")
      @result=@result.paginate(page: params[:page], per_page: 5)
      #@result=@result.paginate(page: params[:page])
      
      #if params[:category_id]
      #  @selcat = Category.find(params[:category_id]) 
      #end
    else
      @ingredients = Ingredient.find(:all,:select=>'name').map(&:name)
      @sources=Source.public_sources.limit(3)
      #@sources2=Source.where("public != ?",true).order("publish_date DESC").paginate(page: params[:page], per_page: 3)
  	end

    #respond_to do |format|
      #format.html { redirect_to root_path, notice: "aaaaaa"  }
      #format.html { render home }
      #format.js { redirect_to root_url}
    #end

  end

  def partnership
    @feedback = Feedback.new
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_countdown.html.erb
<div class="hero-unit center">
	<h1>Bimbyfy</h1>
	
	<!--[if lt IE 9]>
	<p>Data do lançamento: 18/08/2013</p>
	<![endif]-->

	<h2>Segundos para o lançamento:</h2>
	<input type="text" class="dial">
	<h3 id="countdown" style="color: red; margin-top: -120px;"></h3> 
	<div style="margin-top: 120px;"><span class="muted">18-08</span></div>

  <div class="fb-like" data-href="https://www.facebook.com/Bimbyfy" data-width="450" data-layout="button_count" data-show-faces="false" data-send="false"></div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_PT/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</div>

<script>
$(function() {
    $(".dial").knob()
    .trigger(
        'configure',
        {
        "min":0,
        "max":1468800,
        //"fgColor":"#FF0000",
        "bgColor": "#FFFFFF",
        //"skin":"tron",
        "displayInput": false,
        "thickness":".2",
        "angleOffset": "180",
        "inputColor": "#FF0000",
        "cursor": false,
        "readOnly": true//,
        //"width": "200"
        }
    );
});


$(document).ready(function() {
  var secs = parseInt( (new Date('2013-08-18') - new Date() ) * 0.001);
  //var secs = 3600;
  $('#countdown').countdown({
    seconds  : secs,
    callback : function() {
    	location.reload();
      //$('.box').removeClass('active').addClass('inactive');
      //var v=$('.dial').val()-1;
      //$('.dial').val(v).trigger('change');
    }
  });
});

jQuery.fn.extend({
  countdown: function(settings, to) {
    return this.each(function() {
      jQuery.countdown.start(this, settings, to);
    });
  },
  stopCountdown: function() {
    return this.each(function() {
      jQuery.countdown.stop(this);
    });
  }
});

jQuery.extend({
  countdown: {
    settings: {},

    start: function(element, settings, to) {
      if ((typeof this.settings.timerId == 'undefined') ||
          (this.settings.timerId != $(element).data('countdown.id'))) {
        this.settings = jQuery.extend({
          timerId     : new Date().getTime(),
          duration    : 1000,
          seconds     : 10,
          running     : true,
          callback    : function() {}
        }, settings);

        $(element).data('countdown.id', this.settings.timerId);
      }

      settings = this.settings;
      if (!to && to != 0) {
        to = settings.seconds;
      }

      if (settings.running) {
        $(element).text(to);

        $(element).animate({ '' : '' }, settings.duration, '', function() {
          if (settings.running && to > 0) {
            $(this).text(to - 1).countdown(settings, to - 1);
            $('.dial').val(to - 1).trigger('change');
          } else if (settings.running) {
            settings.callback(this);
          }
        });
      }
    },

    stop: function(element) {
      this.settings.running = false;
    }
  }
});
</script>

app/views/static_pages/_rank.html.erb
<li class="span12">
	<% if !signed_in? %>
    	<%= select_tag :source_opt, options_for_select([[t(:source), 0]], params[:source_opt]), name: "s2", class: "span4" %>
	<% else %>
    	<%= select_tag :source_opt, options_for_select([[t(:source), 0], ["Meus #{t(:source)}", 1], [t(:my_cookbook), 2]], params[:source_opt]), name: "s2", class: "span4" %>
	<% end %>
	<%= select_tag :category_opt, options_from_collection_for_select(@cats, :id, :name, params[:category_opt]), prompt: t(:category), class: "span4" %>
	<%= select_tag :order_opt, options_for_select([[t(:ingredient_match), 0], [t(:recipe_percent), 1], [t(:difficulty), 2], [t(:preparation_time), 3]], params[:order_opt]), class: "span4" %>
</li>

<%= render 'result'%>



<script>
  jQuery(function($){
    var url = $(location).attr('href').replace(/&page=[^&;]*/,'');

    $('[name="s1"]').change(function(){
      url = url.replace(/&source_opt=[^&;]*/,'');
      url = url+"&"+jQuery.param({source_opt: $(this).val()});
      window.location.href = url;
    });

    $('[name="s2"]').change(function(){
      url = url.replace(/&source_opt=[^&;]*/,'');
      url = url+"&"+jQuery.param({source_opt: $(this).val()});
      window.location.href = url;
    });


    $("#category_opt").change(function(){
      url = url.replace(/&category_opt=[^&;]*/,'');
      url = url+"&"+jQuery.param({category_opt: $(this).val()});
      window.location.href = url;
    });

    $("#order_opt").change(function(){
      url = url.replace(/&order_opt=[^&;]*/,'');
      url = url+"&"+jQuery.param({order_opt: $(this).val()});
      window.location.href = url;
    });

  });
</script>

app/views/static_pages/_result.html.erb
<% @result.each do |r| %>
<li class="span12">
	<div class="thumbnail">
    <table class="" border="0">
      <tr>
        <td colspan="4">
          <div class="center"><%= get_badge(r[:ratio2]) %></div>
        </td>
      </tr>
      <tr>
        <td rowspan="4" valign="top" class="span2 hidden-phone">
          <%= link_to image_tag(r[:recipe].source.image.to_s, "data-src"=> "holder.js/150x100", size: "150x100 ", alt: r[:recipe].source.name, class: "hidden-phone"), r[:recipe].source if r[:recipe].source.public? %>
        </td>
        <td colspan="2" class="span7">
          <!--<%= link_to "<h5>#{r[:recipe].name}</h5>".html_safe, r[:recipe], class: "" %>
          <%= link_to "<h5>#{r[:recipe].name}</h5>".html_safe, recipe_url("#{r[:recipe].id}-#{r[:recipe].name.downcase.gsub(' ', '-')}"), class: "" %>-->
          <%= link_to "<h5>#{r[:recipe].name}</h5>".html_safe, recipe_url(r[:recipe].link), class: "" %>
        </td>
        <td class="span3">
          <div class="pull-right">
            <% if signed_in? %>
              <% mark_type = "0" %>
              <% mark=current_user.usersmarks.find_by_recipe_id(r[:recipe].id) %>
              <% mark_type=mark.mark_type if mark %>
              <%= button_tag "<i class='icon-star'></i>".html_safe, class: "btn btn-small", id: "#{r[:recipe].id}", name: "fav", "status" => mark_type %>
              <%= button_tag "<i class='icon-shopping-cart'></i>".html_safe, class: "btn btn-small", id: "#{r[:recipe].id}", name: "car", "status" => mark_type %>
            <% end %>
          </div>
        </td>
      </tr>

      <tr>
        <td class="span5">
        <% if r[:recipe].source.public?%>
          <small><%= r[:recipe].pax if r[:recipe].pax %></small>
          <i class="icon-bell"></i>
          <strong><%= r[:recipe].prep_time if r[:recipe].prep_time %></strong>
          <%= "<small>#{r[:recipe].difficult_level}</small>".html_safe if r[:recipe].difficult_level %>                
        <%end%>
        </td>

        <td colspan="2" class="span5">
          <%= link_to r[:recipe].category.name, r[:recipe].category, class: "" %>
        </td>
      </tr>

      <tr class="">
        <td colspan="3" class="span10">
          <p class="muted"><small><%= r[:txt] %></small></p>
        </td>
      </tr>

      <tr>
        <td colspan="3" class="span10">
          <% if r[:recipe].source.public?%>
          	<small class=""><%=link_to r[:recipe].source.name, r[:recipe].source%></small>
          <%else%>
          	<small class=""><%=link_to t(:my_cookbook), r[:recipe].source%></small>
          <%end%>
          <small><%= "#{t(:page)} #{r[:recipe].page}" if r[:recipe].page %></small>
        </td>
      </tr>
    </table>
	</div>
</li>
<% end %>

<div class="center">
    <%= will_paginate @result %>
</div>

<%= render 'usersmarks/form' if signed_in? %>

app/views/static_pages/about.en.html.erb
<% provide(:title, t(:about)) %>
<div class="row offset1">
	<h3 class="" style="text-align:left;">Bimby what!?</h3>
	<blockquote class="">
		<em>Bimbyfy stands for Bimby found you.</em>
		<small>Chris, Bimbyfy founder</small>
	</blockquote>
</div>

<div class="row offset1">
	<h2 class="pull-left" style="text-align:left;"><em>Discover a world of recipes you can cook.</em></h2>
</div>
	
<div class="row span10 offset1">
	<p>
		Bimbyfy is a tool for intelligent search recipes, initially thought to Thermomix recipes, however, open to receive any recipe through registration.
		The main functionality is to search for recipes by ingredients, but you can also search recipes by name, category, book or magazine.
		The website adapts to any screen, allowing a simple and enjoyable navigation. It can be used on a tablet or smartphone as an application.
		In order to ensure copyright, The preparation mode is not published and all the images are provided by Google searches. Registered users can check for recipe in the book or magazine it was published with the page information.
	</p>
	<p>
		Bimbyfy aims to be the largest catalog of recipes on the Internet, indexing the best recipes from specialized cooking magazines and providing innovative features based on a robust search engine.
	</p>
</div>

<div class="row offset1">
	<% if signed_in?%>
		<h2 class="pull-left"><em>Exclusive features</em></h2>
	<%else%>
		<h2 class="pull-left"><em>Make your registration now.</em></h2>
	
	<%end%>
</div>
<div class="span10 offset1">
	<p>
		Registered users have access to the following features:
	</p>
	<ul>
		<li>Select books and magazines to apply filters;</li>
		<li>Mark recipes as favorites;</li>
		<li>Insert recipe preparation mode;</li>
		<li>Send ingredients from recipes to market list;</li>
		<li>Manage market list;</li>
		<li>Create their own recipes.</li>
	</ul>
	
	<% unless signed_in?%>
	<p>
		Click <%= link_to "here", signup_path %> to signup for free.
		
	</p>
	<%end%>
</div>

<div class="row offset1">
	<h2 class="pull-left"><em>Liked! Can I help?</em></h2>
</div>
<div class="span10 offset1">
	<p>Yes! You can donate to contribute for the website maintenance.</p>
	<p>Thanks.</p>
	<%= render 'layouts/donate2' %>
	
</div>

app/views/static_pages/about.html.erb
<% provide(:title, t(:about)) %>
<div class="row offset1">
	<h3 class="" style="text-align:left;">Bimby o quê!?</h3>
	<blockquote class="">
		<em>Bimbyfy stands for Bimby found you.</em>
		<small>Chris, Bimbyfy founder</small>
	</blockquote>
</div>

<div class="row offset1">
	<h2 class="pull-left" style="text-align:left;"><em>Descubra o mundo de receitas que pode fazer<!-- com os ingredientes da sua despensa-->.</em></h2>
</div>
	
<div class="row span10 offset1">
	<p>
		O <%= link_to "Bimby<span class='crd-fy'>fy</span>".html_safe, root_path, id: "logo", class: "brand" %> é uma ferramenta para pesquisa inteligente de receitas culinárias, inicialmente pensado para receitas da Bimby, não obstante, aberto para receber qualquer tipo de receitas através do registo.<!--
		O Bimbify é uma ferramenta de pesquisa inteligente de receitas para a Bimby.--> A principal funcionalidade é a busca de receitas por ingredientes, porém também é possível pesquisar receitas por nome, categoria, livro ou revista.<!--Assim, para que encontre facilmente a receita que procura e, ainda outras alternativas, o Bimbyfy estará constantemente a sincronizar seus conteúdos com os últimos lançamentos de livros e revistas oficiais da Bimby.-->
		O <i>site</i> adapta-se a qualquer ecrã, permitindo assim uma navegação simples e agradável, podendo ser utilizado como se tratasse de uma aplicação em um <i>tablet</i> ou <i>smartphone</i>.<br/>
		No sentido de <u>assegurar a proteção dos direitos de autor</u>, o modo de preparação das receitas não<!--apenas os ingredientes das receitas--> são publicados e as imagens são fornecidas por buscas no Google.<!-- O utilizador poderá consultar em que livro ou revista a receita está publicada encontrando-a rapidamente com a informação da página em que está a receita.--> O utilizador poderá consultar em que livro ou revista a receita está publicada com a informação da página em que esta se encontra.<br/>
	</p>
	<p>
		O Bimbyfy almeja ser o maior catálogo de receitas culinárias na internet, prestando um serviço de indexação das receitas dos melhores livros e revistas especializados e ainda, disponibilizando funcionalidades inovadoras assentes num robusto mecanismo de pesquisa.
		<!--O Bimbyfy quer ser a maior e mais fidedigna fonte de informação acerca de receitas culinárias em português na internet, prestando um serviço de catalogação das receitas dos melhores livros e revistas de culinária.--><br/>
	</p>
</div>

<div class="row offset1">
	<% if signed_in?%>
		<h2 class="pull-left"><em>Funcionalidades exclusivas.</em></h2>
	<%else%>
		<h2 class="pull-left"><em>Faça já o seu registo.</em></h2>
	
	<%end%>
</div>
<div class="span10 offset1">
	<p>
		Os utilizadores registados têm acesso às seguintes funcionalidades:
	</p>
	<ul>
		<li>Seleccionar os livros e revistas que possui para filtrar as pesquisas;</li>
		<li>Marcar receitas como favoritas;</li>
		<li>Inserir modo de preparação das receitas;</li>
		<li>Enviar ingredientes das receitas para lista de compras;</li>
		<li>Gerir lista de compras;</li>
		<li>Criar suas próprias receitas.</li>
	</ul>
	
	<% unless signed_in?%>
	<p>
		Clique <%= link_to "aqui", signup_path %> para criar sua conta.
		
	</p>
	<%end%>
</div>

<div class="row offset1">
	<h2 class="pull-left"><em>Gostei! Posso ajudar?</em></h2>
</div>
<div class="span10 offset1">
	<p>Sim! Poderá contribuir com doações para a manutenção do site.</p>
	<p>A Equipa do Bimbyfy agradece.</p>
	<%= render 'layouts/donate2' %>
	
</div>


<!--
<div class="row offset1">
	<h2 class="pull-left"><em>Seja nosso parceiro!</em></h2>
</div>

<div class="span10 offset1">
	<p>
		Se é editor de livros ou revistas culinárias, ou possui um blog com receitas originais e quer incluir as receitas no Bimbyfy poderá se tornar nosso parceiro. Envie-nos um <a href="mailto:admin@bimbyfy.com?Subject=Parceria" target="_top">email</a> para obter mais informações.
	</p>
</div>
-->
<!--
<div class="row span11 offset1">
</div>
-->
		<!--RETIRAR
		<p>No futuro, em parceria com a Vorwerk, almejamos que a sincronização das receitas seja efectuada em simultâneo com o lançamento de novos livros e revistas oficias da Bimby. E, para os utilizadores registados, permitir a consulta integral da receita e disponibilizar funcionalidade inovadoras.</p>-->

		<!-- COLOCAR ISSO NUM LINK DE PARCERIAS c/FORM p/ CONTACTO
		<p>Se possui um blog com receitas para Bimby de autoria própria e pretender que suas receitas estejam disponíveis nas buscas do Bimbyfy poderá ser nosso parceiro!</p>-->


		<!--NOTAS SOLTAS
		as seguintes funcionalidades: consulta integral da receita; criação de menus semanais e pesquisas avançadas (por calorias, por tempo de preparação ou ainda por rendimento da receita).-->
		<!--Para os utilizadores registados está disponível a criação de menus semanais onde poderão selecionar receitas para cada dia da semana, tendo sempre disponível a lista de ingredientes necessários para efectuar a compra semanal no supermercado.-->

app/views/static_pages/home.html.erb
<% provide(:title, t(:slogan_title)) %>

<% if !assigned_in? %>
	<%= render 'layouts/news' if Time.now.year == 2014 && Time.now.month == 8 %>
	
	<div class="hero-unit center span8 offset1">
    	<h1>Bimby<span class="crd-fy">fy</span></h1>
    	<p class="hidden-phone"><i><%=t :slogan %></i></p>
    	<small class="muted"><%=t :suggest %></small>
    	
    	<%= render 'shared/assignment_form' %>
    
    	<%if Rails.env.production?%>
    		<center>
    			<div class="hidden-phone"><%= render 'layouts/google_plus_1_btn' %></div>
  				<%= render 'layouts/fb_like_btn' %>
  			</center>
  		<%end%>
  	</div>
  	
  	<div class="row-fluid span9 offset1">
  		<div class="">
  			<div class="row-fluid">
  				<div class="span3">
  					<h2><%= t :sources %></h2>

        			<div id="myCarousel" class="carousel slide">
          				<div class="carousel-inner">
          					<% first=true%>
          					<% @sources.each do |s| %>
            					<div class="item <%= "active" if first %>">
              						<!--<%= link_to image_tag(s.image.to_s, "data-src"=> "holder.js/300x200", size: "300x200", alt: "#{s.name}"), sources_path, class: "thumbnail" %>-->
              						<%= link_to image_tag(s.image.to_s, size: "198x240"), sources_path, class: "thumbnail" %>
              						<div class="carousel-caption">
                						<p><%= link_to s.name, s %></p>
              						</div>
            					</div>
            					<% first=false if first%>
          					<% end %>
          				</div>
          				<!-- Carousel nav-->
          				<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
          				<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
        			</div>
      			</div>

      			<div class="span6">
        			<h2><%= t :categories %></h2>
        			<ul class="nav nav-pills ">
        				<% Category.order("name").each do |c| %>
          					<li><%= link_to c.name, c %></li>
        				<% end %>
        			</ul>
      			</div>
      		</div>
	    </div>
  	</div>

  	<div class="span12">
  		<%= render 'shared/advertise_row' %>
  	</div>

<% else %>
	<div class="span12">
		<%= render 'shared/advertise_row' %>
	</div>
	<div class="row-fluid">
    	<%= render 'shared/assignment_form' %>
  	</div>
  
  	<div class="center hero-unit">
    	<p><%= t(:avaible_ingredients) %></p>
    	<div class="row">
      		<ul class="nav">
      			<% current_list.each do |i| %>
        			<li class="label span crd-label"><%= i.html_safe %><%= link_to "&times;".html_safe, remove_path(ingredient_name: i ), method: "delete", class: "close" %></li>
      			<% end %>
      		</ul>
    	</div>
  	</div>

  	<% if @result.size>0 %>
		<ul class="thumbnails">
    		<%= render 'rank' %>
  		</ul>
	<% else %>
    	<span>Nenhuma receita encontrada. <%= link_to "Voltar", root_path %></span>
  	<% end %>
  	
  	<div class="span12">
  		<%= render 'shared/affiliate_row' %>
  	</div>

<% end %>

app/views/static_pages/partnership.html.erb
<% provide(:title, t(:partnership)) %>
<div class="row offset1">
	<h3 class="">Seja nosso Parceiro!</h3>
</div>
<div class="row">	
	<h2 class="text-right offset6 span6"><em>Inclua as suas receitas originais no Bimbyfy.</em></h2>
	<div class="span9 offset2">
		<p>
		Com as parcerias o Bimbyfy pretende expandir suas fontes. Se é um editor de livros e revistas de culinária e quer impulsionar as suas vendas então está no lugar certo. Inclua suas receitas no Bimbyfy!

		<!--Com as parcerias o Bimbyfy pretende expandir suas fontes para os blogues e não só. Se possui um blogue de receitas originais, se tem livros ou revistas publicados, ou se quer ver as receitas daquele seu caderninho que passa de geração à geração nas pesquisas do Bimbyfy, torne-se já nosso parceiro.<br/>
		Cada parceiro poderá publicar, gratuitamente, até 25 receitas originais no seu livro de receitas do Bimbyfy. Seleccione as suas melhores receitas!-->

		<!--As receitas deverão ser de conteúdo partilhado (modo de preparação disponível para consulta). O Bimbyfy fará publicidade aos parcerios colocando sempre um link para o blog ou site do parceiro.-->
		</p>
		<p>
		<p>Para se tornar nosso parceiro, preencha e envie o formulário abaixo. Ser-lhe-á enviado um email com informação acerca do procedimento de envio das receitas.</p>
		<%= render 'shared/feedback_form' %>
	</div>
</div>