config/routes.rb
CrdAppRecipe::Application.routes.draw do
  get "feedbacks/create"

  resources :categories

  resources :sources

  resources :portions

  resources :ingredients

  resources :recipes, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  resources :users
  resources :password_resets

  resources :usersbooks, only: [:create, :destroy]
  resources :usersmarks, only: [:create, :index, :set]
  match '/setitem',  to: 'usersmarks#set'
  resources :feedbacks, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/about',  to: 'static_pages#about'
  match '/partnership',  to: 'static_pages#partnership'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/welcome',  to: 'sources#index'

  resources :assignments, only: [:new, :create, :destroy]
  match '/assignout', to: 'assignments#destroy', via: :delete
  match '/remove', to: 'assignments#remove', via: :delete

  
  match '/:locale', to: 'static_pages#home'
  root to: 'static_pages#home'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :calories, :description, :name,
   :portions, :source_id, :category_id, :note, :shareable,
   :pax, :prep_time, :difficult_level, :page
  has_many :portions, dependent: :destroy
  has_many :ingredients, through: :portions
  has_many :usersmarks#, dependent: :destroy
  has_one :users, through: :sources
  belongs_to :source
  belongs_to :category

  validates :source_id, presence: true
  validates :category_id, presence: true
  validates :name, presence: true, 
            #uniqueness: { case_sensitive: true },
            length: { maximum: 255 }
  validates :description, presence: true

  def list
  	h={}
  	portions.select("part").group("part").order("max(id)").each do |p|
  		if p.part.nil?
  			h[nil] = portions.where("part is null").map {|i| "#{i.portion} #{i.ingredient.name} #{i.note}"}
  		else
  		  h[p.part] = portions.where("part = ?",p.part).map {|i| "#{i.portion} #{i.ingredient.name} #{i.note}"}
  		end
  	end
    h
  end

  def highlight(list)
    s=[]
    portions.each do |p|
      x=0
      list.each do |n|
        x=1 if p.ingredient.name.include?(n.gsub(/%/, ''))
      end
      if list.include?(p.ingredient.name) || x>0
        s.push("<b>#{p.portion} #{p.ingredient.name} #{p.note}</b>")
      else
        s.push("#{p.portion} #{p.ingredient.name} #{p.note}")
      end
    end
    s.join(" | ").html_safe
  end

  def user
    source.user
  end
  
  def link
    #s=self.name.chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s
    s=I18n.transliterate(self.name.downcase).gsub(/[^0-9a-z ]/i, ' ')
    "#{self.id}-#{s.gsub(/\s+/, "-")}"
  
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
	def recipe_correct_user(recipe)
		Recipe.joins(:source).where("user_id = ?",current_user.id).include?(recipe)
	end
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= render 'shared/error_messages', object: f.object if @recipe.errors.any? %>

<div class="well row-fluid">
  <div class="field">
    <%= f.text_field :name, placeholder: "#{t(:new_recipe)}", class: "span12" %>
  </div>

  <% if current_user.admin? %>
  <div class="field">
    <%= f.select :source_id, @sources, class: "span12" %>
  </div>
  <% end %>

  <div class="field">
    <%= f.select :category_id, @categories, class: "span12" %>
  </div>

  <div class="field">
    <%= f.text_area :description, placeholder: "#{t(:preparation)}...", rows: 10, class: "span12" %>
  </div>
  <div class="field">
    <%= f.text_area :note, placeholder: "#{t(:note)}...", rows: 3, class: "span12" %>
  </div>

  <% if current_user.admin? %>
  <div class="field">
    <%= f.label t :calories %>
    <%= f.number_field :calories, class: "span3" %>
  </div>
  <% end %>

<!--
  <label class="checkbox inline">
    <%= f.check_box :shareable %> <%= t :share %>
    <div class="alert"><%= t :sharing_msg %></div>
  </label>
-->
  <div class="actions">
    <%= f.submit t(:save), class: "btn btn-primary" %>
    <%= link_to t(:cancel), :back, class: "btn" %>
  </div>
</div>
<% end %>

app/views/recipes/_recipe.html.erb
<li>
    <div class="thumbnail">
        <table class="" border="0">
        <tr>
            <td rowspan="4" valign="top" class="span2 hidden-phone">
                <%= link_to image_tag(recipe.source.image.to_s, "data-src"=> "holder.js/150x100", size: "150x100 ", alt: recipe.source.name, class: "hidden-phone"), recipe.source if recipe.source.public? %>
            </td>
            <td colspan="2" class="span7">
            	<!--<%= link_to "<h5>#{recipe.name}</h5>".html_safe, recipe, class: "" %>-->
                <!--<%= link_to "<h5>#{recipe.name}</h5>".html_safe, "../receitas/#{recipe.id}", class: "" %>
                <%= link_to "<h5>#{recipe.name}</h5>".html_safe, recipe_url("#{recipe.id}-#{recipe.name.downcase.gsub(' ', '-')}"), class: "" %>-->
                <%= link_to "<h5>#{recipe.name}</h5>".html_safe, recipe_url(recipe.link), class: "" %>
            </td>
            <td class="span3">
                <div class="pull-right">
                <% if signed_in? %>
                    <% mark_type = "0" %>
                    <% mark=current_user.usersmarks.find_by_recipe_id(recipe.id) %>
                    <% mark_type=mark.mark_type if mark %>
                    <%= button_tag "<i class='icon-star'></i>".html_safe, class: "btn btn-small", id: "#{recipe.id}", name: "fav", "status" => mark_type %>
                    <%= button_tag "<i class='icon-shopping-cart'></i>".html_safe, class: "btn btn-small", id: "#{recipe.id}", name: "car", "status" => mark_type %>
                <% end %>
                </div>
            </td>
        </tr>

        <tr>
            <td class="span5">
            <% if recipe.source.public?%>
                <small><%= recipe.pax if recipe.pax %></small>
                <i class="icon-bell"></i>
                <strong><%= recipe.prep_time if recipe.prep_time %></strong>
                <%= "<small>#{recipe.difficult_level}</small>".html_safe if recipe.difficult_level %>
            <%end%>            
            </td>

            <td colspan="2" class="span5">
                <%= link_to recipe.category.name, recipe.category, class: "" %>
            </td>
            
        </tr>
        <tr class="">
            <td colspan="3" class="span10">
                <p class="muted visible-desktop"><small><%= recipe.highlight([""]) %></small></p>
            </td>
        </tr>
        <tr>
            <td colspan="3" class="span10">
            <% if recipe.source.public?%>
                <small class=""><%=link_to recipe.source.name, recipe.source%></small>
            <%else%>
            	<small class=""><%=link_to t(:my_cookbook), recipe.source%></small>
            <%end%>
                <small><%= "#{t(:page)} #{recipe.page}" if recipe.page %></small>
            </td>
        </tr>
        </table>
    </div>
</li>

app/views/recipes/edit.html.erb
<% provide(:title, t(:edit_recipe)) %>
<!--<h1>Editing recipe</h1>-->

<%= render 'form' %>

<!--<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>
<%= link_to t(:back), :back %>-->

app/views/recipes/index.html.erb
<% provide(:title, params[:search] ? "#{t(:search)} #{t(:recipes)} de #{params[:search]}" : t(:recipe_title)) %>
<% provide(:description, params[:search] ? "O Bimbyfy ajuda a encontrar a receita que procura!" : "Pode marcar suas receitas favoritas e adicionar seus ingredientes para a sua lista de compras.") %>
  <%= render 'shared/advertise_row' %>

  <div class="center">
    <h1><%= t(:recipes) %></h1>
    <!--<p><%= "#{@recipes.size} #{t(:recipes)}" if @recipes %></p>-->
  </div>
  

  <% if @recipes.size==0 %>
  	<span>Nenhuma receita encontrada. <%= link_to "Voltar", root_path %></span>
  <% else %>
    <ul class="thumbnails">
      <%= render @recipes.uniq %>
    </ul>
    <div class="center">
      <%= will_paginate @recipes %>
    </div>
  <% end %>
  
  <%= render 'shared/affiliate_row' %>

<%= render 'usersmarks/form' if signed_in? %>

app/views/recipes/new.html.erb
<% provide(:title, t(:new_recipe))  %>
<!--<h1><%= t :new_recipe %></h1>-->

<%= render 'form' %>

<!--<%= link_to 'Back', recipes_path %>
<%= link_to t(:back), :back %>-->

app/views/recipes/show.html.erb
<% provide(:title, @recipe.source.public? ? "#{t(:recipe_title)} - #{@recipe.name}" : "#{t(:my_cookbook)} - #{@recipe.name}") %>
<% provide(:description, @recipe.source.public? ? "Receita de #{@recipe.name}, #{source_type(@recipe.source.name)}, pag. #{@recipe.page}" : "Receita de #{@recipe.name}, carregada pelo utilizador do Bimbyfy") %>
<div itemscope itemtype="http://schema.org/Recipe">
<!--<div vocab="http://schema.org/" typeof="Recipe">-->
      	<% if @recipe.source.public? %>
      	<div class="row">
          	<!--<div class="span3"></div>-->
          	<div class="center span6 hidden-phone">
          		<%= image_tag(@link, alt: @recipe.name, :size => "320x320", class: "thumbnail", itemprop: "image") if@link.length>0 %>
          		<!--<%= image_tag(@link, alt: @recipe.name, :size => "320x320", class: "thumbnail", property: "image") if@link.length>0 %>-->
          		<%= render 'shared/sponsor' %>
          		<table class="table">
          			<tr>
          				<th><i class="icon-th"></i><br><%=t(:produce)%></th>
          				<th><i class="icon-time"></i><br><%=t(:preparation)%></th>
          				<th><i class="icon-wrench"></i><br><%=t(:difficulty)%></th>
          				<th><i class="icon-fire"></i><br><%=t(:calories)%></th>
          			</tr>
          			<tr>
          				<!--<td property="recipeYield"><%= @recipe.pax ? @recipe.pax : "n.d." %></small></td>-->
          				<td><span itemprop="recipeYield"><%= @recipe.pax ? @recipe.pax : "n.d." %></span></td>
          				<td><%= @recipe.prep_time ? @recipe.prep_time : "n.d."  %></td>
          				<!--<td><%= @recipe.prep_time ? "<span property='preptime'>P#{@recipe.prep_time.gsub(' Min', 'M').gsub(' Seg', 'S')}</span>".html_safe : "n.d."  %></td>-->
          				<td><%= @recipe.difficult_level ? @recipe.difficult_level : "n.d." %></td>
          				<td>
          					<!--<div property='nutrition' typeof='NutritionInformation'>-->
          					<div itemprop="nutrition" itemscope itemtype="http://schema.org/NutritionInformation">
          						<!--<span property='calories'>-->
          						<span itemprop="calories">
          							<%= @recipe.calories > 0 ? "#{@recipe.calories}".html_safe : "n.d." if @recipe.calories %>
          						</span>
          					</div>
          				</td>
          			</tr>
          		</table>
          	</div>
          	<div class="offset1 span5 hidden-phone">
          		<%= render 'shared/advertise_column'  %>
          	</div>
          	<div class="center span6 visible-phone">
          		<table class="table">
          			<tr>
          				<th><i class="icon-th"></i><br><%=t(:produce)%></th>
          				<!--<td property="recipeYield"><%= @recipe.pax ? @recipe.pax : "n.d." %></small></td>-->
          				<td><span itemprop="recipeYield"><%= @recipe.pax ? @recipe.pax : "n.d." %></span></td>
          			</tr>
          			<tr>
          				<th><i class="icon-time"></i><br><%=t(:preparation)%></th>
          				<td><%= @recipe.prep_time ? @recipe.prep_time : "n.d."  %></td>
          			</tr>
          			<tr>
          				<th><i class="icon-wrench"></i><br><%=t(:difficulty)%></th>
          				<td><%= @recipe.difficult_level ? @recipe.difficult_level : "n.d." %></td>
          			</tr>
          			<tr>
          				<th><i class="icon-fire"></i><br><%=t(:calories)%></th>
          				<td>
          					<!--<div property='nutrition' typeof='NutritionInformation'>-->
          					<div itemprop="nutrition" itemscope itemtype="http://schema.org/NutritionInformation">
          						<!--<span property='calories'>-->
          						<span itemprop="calories">
          							<%= @recipe.calories > 0 ? "#{@recipe.calories}".html_safe : "n.d." if @recipe.calories %>
          						</span>
          					</div>
          				</td>
          			</tr>
          		</table>
          	</div>
        </div>
        <%end%>

       	<div class="row">
			<!--<h3 class="pull-left" property="name"><%= @recipe.name %></h3>-->
			<h3><span itemprop="name"><%= @recipe.name %></span></h3>
        	<% if signed_in? %>
        		<div class="pull-right">
          			<a href="#" id="fav" class="btn" ><i class="icon-star"></i></a>
          			<a href="#" id="car" class="btn" ><i class="icon-shopping-cart"></i></a>
          		</div>
       		<% end %>
		</div>
		
		
		<div class="row">
				<%if @recipe.source.public?  %>
	        		<p><i><%= link_to @recipe.source.name, @recipe.source %></i>&nbsp;|&nbsp;
       		  		<!--<i><%= link_to @recipe.category.name, @recipe.category, property: "recipeCategory" %></i>&nbsp;|&nbsp;-->
       		  		<i><%= link_to @recipe.category.name, @recipe.category, itemprop: "recipeCategory" %></i>&nbsp;|&nbsp;
       				<i><%= "#{t(:page)} #{@recipe.page}" %></i></p>
       			<%else%>
    				<%= link_to t(:my_cookbook) , @recipe.source %></i>&nbsp;|&nbsp;
       		  		<i><%= @recipe.category.name %></i>
    			<%end%>
    	</div>
    	
		<div class="row">
        	<% if signed_in? && current_user && recipe_correct_user(@recipe) %>
        		<div class="pull-right">
        			<ul class="nav nav-list">
           			<!--<li><%= link_to t(:new_recipe), new_recipe_path(source_id: @recipe.source) %></li>-->
	           			<li><%= link_to "#{t(:edit)} #{t(:ingredients)}", portions_path(recipe_id: @recipe.id)%></li>
    	       			<li><%= link_to "#{t(:edit)} #{t(:recipe)}", edit_recipe_path(@recipe) %></li>
        	   			<li><%= link_to "#{t(:destroy)} #{t(:recipe)}", @recipe, method: :delete, data: { confirm: t(:are_you_sure?) } %></li>
           			</ul>
           		</div>
    	   	<%end%>
       	</div>
        
        
      	<div class="row">
        <div class="well">
        <% @recipe.list.each do |key,value| %>
          <p><b><%= if (key.nil? || key.empty?) then t(:ingredients) else key end %>:</b>
          <% value.each do |v| %>
            <!--<li property="ingredients"><%= v %></li>-->
            <li><span itemprop="ingredients"><%= v %></span></li>
          <% end %>
          </p>
        <% end %>

        <p><b><%= t(:preparation) %>:</b></p>
        <% if !signed_in? %>
        	<div class="alert warning">
        		<!--<%= "<strong>#{t(:copyright_lock)}</strong>".html_safe %>-->
        		<%= render 'shared/regmsg' %>
        		
        	</div>
        <%else%>
        	<%= form_for(current_user.usersmarks.build(recipe_id: @recipe.id), remote: true, :html => { :id => "flags" }) do |f| %>
              <%= f.hidden_field :recipe_id %>
              <%= f.hidden_field :mark_type, value: @mark_type %>
              <% if !@recipe.source.public? || (current_user && current_user.admin?) %>
              <%else%>
              	<%= f.text_area :note, value: @usernote, placeholder: "#{t(:usernote)}...", rows: 15, class: "span11" %>
              <%end%>
              <!--<br/><small><%= t(:click_to_edit) %></small>-->
              <%= f.submit %>
            <% end %>
            <% if !@recipe.source.public? || (current_user && current_user.admin?) %>
            	<p><%= @desc %></p>

          		<% if !@recipe.note.nil? && !@recipe.note.empty? %>
            		<p><b><%= t(:note) %>:</b></br><%= sanitize simple_format(@recipe.note), :tags => %w(b br) %></p>
          		<% end %>

          		<% if @recipe.calories && @recipe.calories>0 %>
            		<p><b><%= t(:calories) %>:</b><%= @recipe.calories %></p>
          		<% end %>
            <%end%>
        <%end%>
        
        </div>
        </div>
        <%= render 'shared/advertise_row' %>
</div>
<script>
  jQuery(function($){
    $("input[type=submit]").hide();
    if( $("#usersmark_mark_type").val() == "0") {
        $("#fav").removeClass("btn-warning");
        $("#car").removeClass("btn-danger");
      } else {
      if( $("#usersmark_mark_type").val() == "1") {
        $("#fav").addClass("btn-warning");
        $("#car").removeClass("btn-danger");
      } else {
      if( $("#usersmark_mark_type").val() == "2") {
        $("#fav").removeClass("btn-warning");
        $("#car").addClass("btn-danger");
      } else {
      if( $("#usersmark_mark_type").val() == "3") {
        $("#fav").addClass("btn-warning");
        $("#car").addClass("btn-danger");
      }}}}

    $("#fav").click(function(){
      if( $("#usersmark_mark_type").val() == "0") {
        $("#usersmark_mark_type").val("1");
        $(this).addClass("btn-warning");
      } else {
      if( $("#usersmark_mark_type").val() == "1") {
        $("#usersmark_mark_type").val("0");
        $(this).removeClass("btn-warning");
      } else {
      if( $("#usersmark_mark_type").val() == "2") {
        $("#usersmark_mark_type").val("3");
        $(this).addClass("btn-warning");
      } else {
      if( $("#usersmark_mark_type").val() == "3") {
        $("#usersmark_mark_type").val("2");
        $(this).removeClass("btn-warning");
      }}}}
      //$(this).closest("form").submit();
      $("#flags").submit();
    });

    $("#car").click(function(){
      if( $("#usersmark_mark_type").val() == "0") {
        $("#usersmark_mark_type").val("2");
        $(this).addClass("btn-danger");
      } else {
      if( $("#usersmark_mark_type").val() == "1") {
        $("#usersmark_mark_type").val("3");
        $(this).addClass("btn-danger");
      } else {
      if( $("#usersmark_mark_type").val() == "2") {
        $("#usersmark_mark_type").val("0");
        $(this).removeClass("btn-danger");
      } else {
      if( $("#usersmark_mark_type").val() == "3") {
        $("#usersmark_mark_type").val("1");
        $(this).removeClass("btn-danger");
      }}}}
      //$(this).closest("form").submit(); 
      $("#flags").submit();
    });

    //$("#usersmark_note").attr('title', '<%= t(:click_to_edit)%>');
    $("#usersmark_note").prop('readonly', true);
    $("#usersmark_note").click(function() {
      $(this).prop('readonly', false);
      //$(this).attr('title','');
    });

    $("#usersmark_note").change(function(){
      $(this).prop('readonly', true);
      //$(this).attr('title', '<%= t(:click_to_edit)%>');
      $("#flags").submit();
    });
     $("#usersmark_note").blur(function() {
      $(this).prop('readonly', true);
      //$(this).attr('title','');
    });

  });
</script>