config/routes.rb
CrdAppRecipe::Application.routes.draw do
  get "feedbacks/create"

  resources :categories

  resources :sources

  resources :portions

  resources :ingredients

  resources :recipes, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  resources :users
  resources :password_resets

  resources :usersbooks, only: [:create, :destroy]
  resources :usersmarks, only: [:create, :index, :set]
  match '/setitem',  to: 'usersmarks#set'
  resources :feedbacks, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/about',  to: 'static_pages#about'
  match '/partnership',  to: 'static_pages#partnership'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/welcome',  to: 'sources#index'

  resources :assignments, only: [:new, :create, :destroy]
  match '/assignout', to: 'assignments#destroy', via: :delete
  match '/remove', to: 'assignments#remove', via: :delete

  
  match '/:locale', to: 'static_pages#home'
  root to: 'static_pages#home'

end

app/views/shared/_advertise_column.html.erb
<div class="visible-desktop" >
	<%if Rails.env.production?%>
		<%= render 'layouts/ads6'  %>
	<%else%>
		<!--<div style="background-color: gray; width:300px; height:250px;"><h2>Afiliados</h2></div>-->
		<div style="background-color: gray; width:336px; height:280px;"><h2>Adsense</h2></div>
	<%end%>
	<!--<span class="span4"><small>Ajude a manter o Bimbyfy!</small></span>
  	<%= render 'layouts/donate' %>-->

</div>

app/views/shared/_advertise_row.html.erb
<div class="hidden-phone">
	<%if Rails.env.production?%>
		<%= render 'layouts/ads1'  %>
	<%else%>
		<center>
			<div style="background-color: gray; width:728px; height:90px;"><h2>Adsense</h2></div>
		</center>
	<%end%>
</div>
<br/>

app/views/shared/_advertise_row2.html.erb
<div class="hidden-phone ">
	<center>
		<div id="myAdCarousel" class="carousel slide carousel-fade">
			<div class="carousel-inner">
				<div class="item active">
					<%if Rails.env.production?%>
						<%= render 'layouts/ads1'  %>
					<%else%>
						<div style="background-color: gray; width:728px; height:90px;"><h2>Adsense</h2></div>
					<%end%>
				</div>
				<div class="item">
					<%if Rails.env.production?%>
						<%= render 'layouts/zanox_grouponPT'%>
					<%else%>
						<div style="background-color: gray; width:728px; height:90px;"><h2>Afiliados</h2></div>
					<%end%>
				</div>
			</div>
		</div>
	</center>
</div>
<script>
$('#myAdCarousel').carousel({
	interval: 4000
})
</script>

app/views/shared/_affiliate_row.html.erb
<div class="hidden-phone">
	<%if Rails.env.production?%>
		<%= render 'layouts/zanox_grouponPT'%>
	<%else%>
		<center>
			<div style="background-color: gray; width:728px; height:90px;"><h2>Afiliados</h2></div>
		</center>
	<%end%>
</div>
<br/>

app/views/shared/_assignment_form.html.erb
<% unless home_page? %>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Dica!</strong> <%=@tip.html_safe %>
</div>
<% end %>
<%= form_for(:assignment, url: assignments_path) do |i| %>
	<div class="field">
	    <%= i.text_field :name, "autocomplete"=>"off", class: "span4 mt", "data-provide"=>"typeahead"%>
	    <%= i.submit t(:add), class: "btn btn-primary" %>
    	<%= link_to t(:clear), assignout_path, method: "delete", class: "btn btn-danger" if !home_page? %>
  	</div>
  	
<% end %>

<%= javascript_tag "var ingredients = #{ @ingredients.to_json };" %>
<script>
$('.mt').typeahead({
	source: ingredients,
	items: 5,
	matcher: function(item) {
		var q=this.query.latinize()
		var i=item.latinise()
		if (i.toLowerCase().indexOf(q.trim().toLowerCase()) == 0) {
			return true
		}
    }
})

</script>

<!--
<script>
//jQuery($(function () {
  $('.popover-test').popover({ 
    class: "hidden-phone",
    html : true,
    title: "<strong>Dica!</strong>",
    //content: "Para pesquisar qualquer tipo de queijo basta adicionar <u>queijo%</u>",
    placement: "right"
  }).popover('show');

//});
//  );
</script>
-->

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="accordion" id="accordion2">
    <div class="accordion-group">
      <div class="accordion-heading">
        <div class="alert alert-error">
          <span><%= t(:error_msg) %></span>
          <a class="accordion-toggle span pull-right" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne"><%= t(:details) %></a>
        </div>  
      </div>
      <div id="collapseOne" class="accordion-body collapse">
        <div class="accordion-inner">
          <ul>
          <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<!--
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>-->
<% end %>

app/views/shared/_feedback_form.html.erb
<%= form_for(@feedback) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
 <div class="field">
 	<%= f.label :name %>
  	<%= f.text_field :name %>
  	<%= f.label :email %>
  	<%= f.text_field :email %>
  	<%= f.hidden_field :message, value:"." %>
  	<%= check_box_tag 'accept' %> Concordo com os Termos e Condições
	<%= f.submit t(:send), class: "btn btn-large btn-primary", disabled: true %>
  </div>
  

<% end %>

<script>
  $("input[type=checkbox]").click(function(){
      if($(this).is(':checked')) {
      	//alert("accepted!");
      	$('input[type="submit"]').removeAttr('disabled');
  	  } else {
  	  	$('input[type="submit"]').attr('disabled','disabled');
  	  }
    });
</script>

<div class="well">
<p><strong><u>Termos e Condições das Parcerias</u></strong></p>
<ol>
<li>O Bimbyfy só aceita parceiros com conteúdos originais. Caso seja detectada alguma cópia a parceria é desfeita e os conteúdos elimidados.</li>
<li>Os parceiros são responsáveis pelas suas receitas, tanto à nivel da prepação quanto à nivel de conteúdos. O Bimbyfy não se responsabiliza pelas receitas dos parceiros.</li>
<li>Cada parceiro terá disponivel um livro de receitas no Bimbyfy com até 25 receitas. <!--Se pretenderem inserir mais que 25 receitas deverão optar pelos planos pagos.--></li>
<!--
<li>Os parceiros deverão enviar suas receitas num ficheiro de texto simples com as seguintes informações para cada receita:
<ul><li>Categoria</li><li>Nome</li><li>Rendimento</li><li>Lista de ingredientes</li><li>Modo de preparação</li><li>Dicas *</li><li>Calorias *</li><li>Página *</li></ul>
<small>* informação opcional.</small></li>
<li>O Bimbyfy validará o ficheiro com as receitas do parceiro e irá inserir seus conteúdos na base de dados. Caso existam anomalias no ficheiro o parceiro será contactado.</li>
<li>Juntamente com o ficheiro o parceiro deverá informar o título do seu livro de receitas. Caso se trate de um blogue o título deverá corresponder à URL.</li>-->
<li>Os parceiros receberão um email de boas-vindas que irá conter indicações sobre o procedimento do envio das receitas.</li>
</div>

app/views/shared/_regmsg.html.erb
	<h3><em>Faça já o seu registo.</em></h3>
	<!--<hr class="featurette-divider">-->
	<p>
		Os utilizadores registados têm acesso às seguintes funcionalidades:
	</p>
	<ul>
		<li>Seleccionar os livros e revistas que possui para filtrar as pesquisas;</li>
		<li>Marcar receitas como favoritas;</li>
		<li>Inserir modo de preparação das receitas;</li>
		<li>Enviar ingredientes das receitas para lista de compras;</li>
		<li>Gerir lista de compras;</li>
		<li>Criar suas próprias receitas.</li>
	</ul>
	
	<%= link_to "Criar #{t(:sign_up)}!", signup_path, class: 'btn btn-large btn-danger' %>
	<%= link_to "Saber mais", about_path, class: 'btn ' %>

app/views/shared/_sponsor.html.erb
<small><%="#{t(:sponsor)} #{image_tag('https://www.google.com/uds/css/small-logo.png')}".html_safe %></small>