config/routes.rb
CrdAppRecipe::Application.routes.draw do
  get "feedbacks/create"

  resources :categories

  resources :sources

  resources :portions

  resources :ingredients

  resources :recipes, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  resources :users
  resources :password_resets

  resources :usersbooks, only: [:create, :destroy]
  resources :usersmarks, only: [:create, :index, :set]
  match '/setitem',  to: 'usersmarks#set'
  resources :feedbacks, only: [:create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/about',  to: 'static_pages#about'
  match '/partnership',  to: 'static_pages#partnership'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/welcome',  to: 'sources#index'

  resources :assignments, only: [:new, :create, :destroy]
  match '/assignout', to: 'assignments#destroy', via: :delete
  match '/remove', to: 'assignments#remove', via: :delete

  
  match '/:locale', to: 'static_pages#home'
  root to: 'static_pages#home'

end

app/views/layouts/_ads1.html.erb
<center>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8699151811109863";
/* Bimbyfy ads1 */
google_ad_slot = "9824328882";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<center>

app/views/layouts/_ads3.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8699151811109863";
/* Bimbyfy ads3 */
google_ad_slot = "3736998883";
google_ad_width = 300;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/_ads4.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8699151811109863";
/* Bimbyfy ads4 */
google_ad_slot = "1562261682";
google_ad_width = 250;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/_ads5.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8699151811109863";
/* Bimbyfy ads5 */
google_ad_slot = "5678600082";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/_ads6.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8699151811109863";
/* Bimbyfy ads6 */
google_ad_slot = "2505423284";
google_ad_width = 336;
google_ad_height = 280;
//-->
</script>
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/_browsercheck.en.html.erb
<!--[if lt IE 9 ]>
	<div class="alert alert-block">
  		<button type="button" class="close" data-dismiss="alert">&times;</button>
  		<h4>Warning!</h4>
  		Your browser is out of date. It has known security flaws and may not display all features of this and other websites. 
  		Please update your browser <a target='_blank' href='http://whatbrowser.org/intl/en/'>here</a>.
	</div>
<![endif]-->

app/views/layouts/_browsercheck.html.erb
<!--[if lt IE 9 ]>
	<div class="alert alert-block">
  		<button type="button" class="close" data-dismiss="alert">&times;</button>
  		<h4>Importante!</h4>
  		Seu navegador está desatualizado. Ele possui falhas de segurança e pode apresentar problemas para exibir este e outros websites.
  		Recomendamos que actualize o seu navegador <a target='_blank' href='http://whatbrowser.org/'>aqui</a>.
	</div>
<![endif]-->

app/views/layouts/_donate.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="Z3F47KQZ479BN">
<input type="image" src="https://www.paypalobjects.com/pt_PT/PT/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - A maneira mais fácil e segura de efetuar pagamentos online!">
<img alt="" border="0" src="https://www.paypalobjects.com/pt_PT/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/layouts/_fb.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_PT/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_fb_like_box.html.erb
<%if Rails.env.production? %>
	<div class="fb-like-box" data-href=" www.facebook.com/Bimbyfy" data-width="292" data-show-faces="true" data-stream="false" data-show-border="false" data-header="true"></div>
<%else%>
	<div style="background-color: gray; width:292px; height:300px;"><h2>fBox</h2></div>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="row-fluid">
	<div class="span4">developed by <b><a href="http://cristheinz.info" target="_blank">cristheinz</a></b></div>

    <ul class="nav nav-pills pull-right">
    	<li><%= link_to t(:ingredients), ingredients_path unless URI(request.url).path.to_s.include?("ingredient") %></li>
      	<li><%= link_to t(:about), about_path unless URI(request.url).path.to_s.include?("about") %></li>
      	<!--<li><%= link_to t(:partnership), partnership_path unless URI(request.url).path.to_s.include?("partnership") %></li>-->
      	<li><%= link_to t(:home), assignout_path, method: "delete" if !home_page? %></li>
    </ul>
	
	<div class="row offset5 span5">
		<small>since <%=@since%> ago</small>
	</div> 	

</footer>

<!--<div id="fim">Deus seja louvado</div>
<div class="crd-footer hidden-desktop row-fluid">
    <ul class="nav nav-pills pull-right">
      <li><%= link_to t(:about), about_path unless URI(request.url).path.to_s.include?("about") %></li>
      <li><%= link_to t(:partnership), partnership_path unless URI(request.url).path.to_s.include?("partnership") %></li>
      <li><%= link_to t(:home), assignout_path, method: "delete" if !home_page? %></li>
    </ul>

	<div class="span3">
  		<p>developed by <b>cristheinz</b></p>
 	</div>

</div>-->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Bimby<span class='crd-fy'>fy</span>".html_safe, root_path, id: "logo", class: "brand" %>
      <div class="nav-collapse collapse">

        <ul class="nav pull-right">
          <% if signed_in?%>
            <li class="divider-vertical visible-desktop"></li>
            <li id="fat-menu" class="dropdown visible-desktop">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
              <ul class="dropdown-menu">
              	<li><%= link_to t(:my_cookbook), current_user.sources.first unless current_user.admin? %></li>
              	
                <li><%= link_to t(:sources), sources_path %></li>
                <li><%= link_to t(:categories), categories_path if current_user.admin? %></li>
                <li><%= link_to t(:recipes), recipes_path  unless current_user.admin?%></li>
                <li><%= link_to t(:ingredients), ingredients_path if current_user.admin? %></li>
                <li><%= link_to t(:shopping_list), usersmarks_path unless current_user.admin?%></li>
                
                <li class="divider"></li>
                <li><%= link_to t(:settings), edit_user_path(current_user) %></li>
                <li><%= link_to t(:sign_out), signout_path, method: "delete" %></li>
              </ul>
            </li>

			<li class="hidden-desktop"><%= link_to t(:my_cookbook), current_user.sources.first unless current_user.admin? %></li>
            <li class="hidden-desktop"><%= link_to t(:categories), categories_path if current_user.admin? %></li>
            <li class="hidden-desktop"><%= link_to t(:sources), sources_path %></li>
            <li class="hidden-desktop"><%= link_to t(:recipes), recipes_path %></li>
            <li class="hidden-desktop"><%= link_to t(:shopping_list), usersmarks_path %></li>
            <li class="hidden-desktop"><%= link_to t(:settings), edit_user_path(current_user) %></li>
            <li class="hidden-desktop"><%= link_to t(:sign_out), signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to t(:sign_in), signin_path %></li>
          <% end %>
        </ul>

        <%= form_tag(recipes_path, :method => :get, class: "navbar-search pull-right", id: "peq" ) do %>
          <%= text_field_tag :search, "", class: "search-query span3", "placeholder" => t(:search) %>
          <%= hidden_field_tag :locale, params[:locale] %>
        <% end %>

      </div>
    </div>
  </div>
</header>

<script>
  jQuery(function($){
    $("#peq").submit(function(){
      if( $("#search").val().length < 3 ) {
        $("#search").val("");
        return false;
      } else {
        return true;
      }
    });
  });
</script>

app/views/layouts/_news.html.erb
<div class="visible-desktop">
	<!--LINK: http://www.webestools.com/ribbon-generator-web20-free-online-quickribbon-generator.html-->
	<script type="text/javascript" src="http://services.webestools.com/ribbons/ribbon.js?texte=1%C2%BA%20Anivers%C3%A1rio&lien=&color=%23FCFCFC&type=fixed&pos=right&size=20&font=arial&style=11"></script>
</div>
<!--<div class="visible-desktop" style="position:absolute;right:0px;margin-right:0%;margin-top:0px; background-color: gray; width:200px; height:200px;">
	<%=image_tag("news2.jpg")%>
		
</div>-->

app/views/layouts/_zanox_grouponPT.html.erb
<a href="http://ad.zanox.com/ppc/?27312597C864919102T"><img src="http://ad.zanox.com/ppv/?27312597C864919102" align="bottom" width="728" height="90" border="0" hspace="1" alt="728 x 90 Shopping"></a>